name: test-self-hosted-runner

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  wget_alias: 'wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0'
  ARCH: x86
  board: DELL

jobs:
  build-all-os:
    runs-on: [self-hosted, test]
    permissions:
      contents: read
    steps:
        - run: echo "Hello from $HOSTNAME"

        - name: echo "run scripts from runner"
          run:  bash /workspace/rustci-self-hosted-runner/entrypoint.sh

