name: test-self-hosted-runner

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  ARCH: x86
  board: DELL

jobs:
  Rustci:
    runs-on: [self-hosted, test]
    permissions:
      contents: read
    steps:
        - run: echo "Hello from $HOSTNAME"

        - name: echo "run scripts from runner"
          run:  bash /home/GHA/tank/entrypoint.sh
